functionsDirectory = "C:\\Users\\pete\\Documents\\MciPro\\netlify\\functions"
functionsDirectoryOrigin = "config"
headersOrigin = "config"
redirectsOrigin = "config"
plugins = []

[build]
publish = "C:\\Users\\pete\\Documents\\MciPro"
publishOrigin = "config"
commandOrigin = "config"
command = "echo 'Static site ready for deployment'"
functions = "C:\\Users\\pete\\Documents\\MciPro\\netlify\\functions"

[build.environment]
NODE_VERSION = "20"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]
node_bundler = "esbuild"

[[headers]]
for = "/index.html"

[headers.values]
Cache-Control = "no-cache, no-store, must-revalidate"
Pragma = "no-cache"
Expires = "0"

[[headers]]
for = "/chat/*.js"

[headers.values]
Content-Type = "text/javascript; charset=utf-8"
Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
for = "/chat/*.css"

[headers.values]
Content-Type = "text/css; charset=utf-8"

[[headers]]
for = "/*.js"

[headers.values]
Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
for = "/.netlify/functions/*"

[headers.values]
Access-Control-Allow-Origin = "*"
Access-Control-Allow-Methods = "GET, PUT, POST, OPTIONS"
Access-Control-Allow-Headers = "Content-Type, Authorization, X-User-Id"

[[redirects]]
from = "/chat/*"
to = "/chat/:splat"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/*"
to = "https://mycaddipro.com/:splat"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]
Host = ["www.mycaddipro.com", "mcipro-golf-platform.netlify.app"]

[redirects.headers]

[[redirects]]
from = "http://mycaddipro.com/*"
to = "https://mycaddipro.com/:splat"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]