[build]
  publish = "."
  command = "echo 'Static site ready for deployment'"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Serve real files under /chat/ as-is (no SPA rewrite)
[[redirects]]
  from = "/chat/*"
  to = "/chat/:splat"
  status = 200
  force = true

# TEMPORARILY DISABLED - Let files load directly
# SPA fallback LAST
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

[[headers]]
  for = "/chat/*.js"
  [headers.values]
    Content-Type = "text/javascript; charset=utf-8"
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/chat/*.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, PUT, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-User-Id"

[build.environment]
  NODE_VERSION = "20"
# Deploy trigger: Tue, Oct 14, 2025  9:15:00 AM

# Canonical host and HTTPS enforcement
[[redirects]]
  from = "/*"
  to = "https://mycaddipro.com/:splat"
  status = 301
  force = true
  conditions = { Host = ["www.mycaddipro.com", "mcipro-golf-platform.netlify.app"] }

[[redirects]]
  from = "http://mycaddipro.com/*"
  to = "https://mycaddipro.com/:splat"
  status = 301
  force = true