[build]
  publish = "."
  command = "echo 'Static site ready for deployment'"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, PUT, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-User-Id"

[build.environment]
  NODE_VERSION = "20"