name = "mcipro-sync"
main = "src/worker.js"
compatibility_date = "2024-01-01"

[vars]
API_KEY = "mcipro-sync-key-2024"

[[kv_namespaces]]
binding = "MCIPRO_SYNC"
preview_id = "c177a59213c84bcfa6cc9fae2af3f225"
id = "c177a59213c84bcfa6cc9fae2af3f225"