version: "3.9"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: chatpass
      POSTGRES_USER: chatuser
      POSTGRES_DB: chatdb
    ports: ["5432:5432"]
  redis:
    image: redis:7
    ports: ["6379:6379"]
  localstack:
    image: localstack/localstack:3
    environment:
      SERVICES: sqs
    ports: ["4566:4566"]
